### ISSUE TITLE
does not accept spaces in file path

### ISSUE THREAD

**Issue by TheAugoosetus** [adierking/unplug#1]
You may already know this, but when using `unplug config set default-iso`, the program will not work if you have a space in any folder names. For example, I had my path set as C:\Users\okaug\Desktop\Pikmin PIA\Roms\chibi-robo\chibi-robo.iso, but I was greeted with `error: Found argument 'PIA\Roms\chibi-robo\cheebo.iso' which wasn't expected, or isn't valid in this context` when I ran the command. However, changing it to C:\Users\okaug\Desktop\Gaming\roms\chibi-robo.iso worked. This also happened when I tried running `unplug config set dolphin-path 'C:\Users\okaug\Desktop\Pikmin PIA\Tools\Dolphin 5.0\dolphin.exe'`, which gave the same error code (`error: Found argument 'PIA\Tools\Dolphin' which wasn't expected, or isn't valid in this context`).

**Comment by adierking** [comment]
Hi! Congrats on being the first person to file an issue 😁

This is a consequence of how command-line programs work in general - the OS splits your command apart at spaces, and the program sees those groups as individual parameters. Unfortunately there isn't really an easy way for me to make this better. For example, it wouldn't be correct to assume that multiple parameters have spaces between them because we don't actually know what the original command looked like.

The best way to work around this is to surround your path with double quotes, which prevents the OS from splitting the text up:
```
$ unplug config set default-iso "C:\Users\okaug\Desktop\Pikmin PIA\Roms\chibi-robo\chibi-robo.iso"
```

**Comment by adierking** [comment]
BTW, I'll update the docs to use double-quotes because that works better on Windows I think - I tend to use Linux so I forget these things 😅
